project:
  type: website

website:
  title: "Exploring Photoreceptor Contributions to Leaf Growth: Examining the Effect of Phytochrome B"
  navbar:
    left:
      - href: Paper.qmd
        text: Home
